//! The smallest scene that exercises the editor.
//!
//! The demo scene is a rendering proof: eight entities, five of them the same
//! sprite five times, tuned so transparency ordering is visible. Testing the
//! editor against it means every assertion carries the demo's choices, and
//! retuning the demo breaks the editor's tests for no reason.
//!
//! This is the other thing: one cube, one still sprite, one sprite that plays a
//! sheet, and the cameras they need. It exists to be asserted about, so it holds
//! one of each rather than a composition. Open it by hand with
//! `cargo run -p sindri-editor -- editor/assets/fixture.scene.json`.
//!
//! ## Why two cameras
//!
//! "One camera" is not enough and cannot be. A mesh needs a world camera or
//! extraction fails with `MissingWorldCamera`; a sprite resolves its anchor
//! against the overlay camera's extent and fails with `MissingOverlayCamera`
//! without one. A scene holding both a cube and a sprite therefore holds a
//! perspective camera and an orthographic one. Two is the minimum, not a
//! convenience.
//!
//! ## Textures
//!
//! The fixture is self-contained: `procedural:checkerboard` is generated by the
//! engine, and `textures/badge.png` and `textures/spin.png` are real files
//! sitting beside the scene, loaded from there like any other project's. A
//! reference that resolved to none of them would still draw, as the
//! missing-texture checker; that is a property worth having and a poor thing to
//! open the editor into, so a test holds the fixture to naming only textures
//! that resolve.
//!
//! `spin.png` is a two-by-two sheet whose four cells put a coloured dot at each
//! quarter of a turn, so pressing Play visibly spins it and a still of the sheet
//! says which cell is which.

use std::path::PathBuf;

use crate::scene_file::{SceneFile, SceneFileError};

/// Where the fixture lives, relative to the repository root.
///
/// This is the path a person types. [`path`] is the one code should use.
pub const FIXTURE_SCENE_PATH: &str = "editor/assets/fixture.scene.json";

/// The fixture's location on this machine.
///
/// Resolved against the crate rather than the working directory, so a test
/// finds it whatever directory the test runner chose.
pub fn path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("assets")
        .join("fixture.scene.json")
}

/// Opens the fixture through the same path the editor opens any scene.
pub fn open() -> Result<SceneFile, SceneFileError> {
    SceneFile::open(path())
}
