[package]
name = "weave-poc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sindri-core = { path = "../../crates/sindri-core" }
sindri-weave = { path = "../../crates/sindri-weave" }
weave = { path = "../../weave/crates/weave" }

[lints]
workspace = true
