{
  "format_version": 1,
  "name": "Last Stand Synergies",
  "type": "synergy_catalog",
  "values": {
    "synergies": [
      {
        "key": "synergy_forked_guidance",
        "name": "FORKED GUIDANCE",
        "required_0": "shots",
        "minimum_0": 2,
        "required_1": "missile",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_critical_conduction",
        "name": "CRITICAL CONDUCTION",
        "required_0": "crit",
        "minimum_0": 0.001,
        "required_1": "arc",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_mass_driver",
        "name": "MASS DRIVER",
        "required_0": "bullet_size",
        "minimum_0": 1.001,
        "required_1": "bullet_speed",
        "minimum_1": 9.001,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_phase_discharge",
        "name": "PHASE DISCHARGE",
        "required_0": "pierce",
        "minimum_0": 1,
        "required_1": "nova",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_prismatic_phase",
        "name": "PRISMATIC PHASE",
        "required_0": "pierce",
        "minimum_0": 1,
        "required_1": "beam",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_hunters_spark",
        "name": "HUNTER'S SPARK",
        "required_0": "comp_ember",
        "minimum_0": 1,
        "required_1": "missile",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_phase_escort",
        "name": "PHASE ESCORT",
        "required_0": "comp_drone",
        "minimum_0": 1,
        "required_1": "pierce",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_heavy_orbit",
        "name": "HEAVY ORBIT",
        "required_0": "comp_blade",
        "minimum_0": 1,
        "required_1": "bullet_size",
        "minimum_1": 1.001,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_void_echo",
        "name": "VOID ECHO",
        "required_0": "comp_wisp",
        "minimum_0": 1,
        "required_1": "nova",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_static_aegis",
        "name": "STATIC AEGIS",
        "required_0": "comp_shield",
        "minimum_0": 1,
        "required_1": "arc",
        "minimum_1": 1,
        "required_2": "",
        "minimum_2": 0,
        "required_3": "",
        "minimum_3": 0,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_seeking_storm",
        "name": "SEEKING STORM",
        "required_0": "shots",
        "minimum_0": 2,
        "required_1": "missile",
        "minimum_1": 1,
        "required_2": "arc",
        "minimum_2": 1,
        "required_3": "transform_storm",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_critical_mass",
        "name": "CRITICAL MASS",
        "required_0": "bullet_size",
        "minimum_0": 1.001,
        "required_1": "crit",
        "minimum_1": 0.001,
        "required_2": "nova",
        "minimum_2": 1,
        "required_3": "transform_critical_mass",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_rail_prism",
        "name": "RAIL PRISM",
        "required_0": "bullet_speed",
        "minimum_0": 9.001,
        "required_1": "pierce",
        "minimum_1": 1,
        "required_2": "beam",
        "minimum_2": 1,
        "required_3": "transform_rail_prism",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_recursive_violence",
        "name": "RECURSIVE VIOLENCE",
        "required_0": "shots",
        "minimum_0": 2,
        "required_1": "pierce",
        "minimum_1": 1,
        "required_2": "missile",
        "minimum_2": 1,
        "required_3": "arc",
        "minimum_3": 1,
        "required_4": "transform_recursive",
        "minimum_4": 1
      },
      {
        "key": "synergy_event_horizon",
        "name": "EVENT HORIZON",
        "required_0": "bullet_size",
        "minimum_0": 1.001,
        "required_1": "nova",
        "minimum_1": 1,
        "required_2": "mines",
        "minimum_2": 1,
        "required_3": "pierce",
        "minimum_3": 1,
        "required_4": "transform_horizon",
        "minimum_4": 1
      },
      {
        "key": "synergy_thunder_choir",
        "name": "THUNDER CHOIR",
        "required_0": "arc",
        "minimum_0": 1,
        "required_1": "comp_ember",
        "minimum_1": 1,
        "required_2": "comp_wisp",
        "minimum_2": 1,
        "required_3": "transform_thunder_choir",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_prismatic_razor",
        "name": "PRISMATIC RAZOR",
        "required_0": "comp_blade",
        "minimum_0": 1,
        "required_1": "beam",
        "minimum_1": 1,
        "required_2": "bullet_speed",
        "minimum_2": 9.001,
        "required_3": "transform_razor_prism",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_guardian_swarm",
        "name": "GUARDIAN SWARM",
        "required_0": "comp_shield",
        "minimum_0": 1,
        "required_1": "comp_drone",
        "minimum_1": 1,
        "required_2": "shots",
        "minimum_2": 2,
        "required_3": "transform_guardian_swarm",
        "minimum_3": 1,
        "required_4": "",
        "minimum_4": 0
      },
      {
        "key": "synergy_singularity_court",
        "name": "SINGULARITY COURT",
        "required_0": "comp_wisp",
        "minimum_0": 1,
        "required_1": "mines",
        "minimum_1": 1,
        "required_2": "nova",
        "minimum_2": 1,
        "required_3": "bullet_size",
        "minimum_3": 1.001,
        "required_4": "transform_singularity_court",
        "minimum_4": 1
      }
    ]
  }
}
