//! The same description, rendered for a person.
//!
//! Generated from the same model as the JSON rather than written beside it: a
//! prose reference that drifts from the machine-readable one is worse than no
//! prose reference, because a reader has no way to tell which of the two lied.

use std::fmt::Write as _;

use crate::decay::{DecayApi, Namespace, Symbol};

/// Renders the Decay surface as Markdown.
pub(crate) fn render(api: &DecayApi) -> String {
    let mut page = String::new();

    page.push_str(&preamble());
    page.push_str(
        "## `this`\n\nWhat the entity a script runs on offers, beyond the script's own fields.\n\n",
    );
    push_symbols(&mut page, &api.this);

    page.push_str("\n## Globals\n\nNames in scope without qualification. Decay has no imports, so each of these is a name a script cannot use for its own.\n\n");
    push_symbols(&mut page, &api.globals);

    page.push_str("\n## Types\n");
    for namespace in &api.types {
        push_namespace(&mut page, namespace);
    }

    page
}

fn preamble() -> String {
    format!(
        "# Decay host API\n\n\
         <!-- Generated by `{command}`. Do not edit by hand: a test fails when\n\
         this file disagrees with the host surface in `sindri-decay`. -->\n\n\
         Every namespace, call, and member a Decay script may name in this build\n\
         of the engine, derived from the one description the analyzer\n\
         type-checks against and the runtime host answers.\n\n\
         Parameter *names* are not recorded — the host surface registers types,\n\
         because that is what type-checking needs. What each argument means is\n\
         in [`docs/scripting.md`](../scripting.md).\n\n\
         The machine-readable form of this page is\n\
         [`decay-api.json`](decay-api.json).\n\n",
        command = crate::REGENERATE_COMMAND,
    )
}

fn push_namespace(page: &mut String, namespace: &Namespace) {
    let _ = write!(page, "\n### `{}`\n\n", namespace.name);
    if namespace.members.is_empty() {
        page.push_str("The host names this type but has not described its members.\n");
        return;
    }
    push_symbols(page, &namespace.members);
}

fn push_symbols(page: &mut String, symbols: &[Symbol]) {
    if symbols.is_empty() {
        page.push_str("Nothing.\n");
        return;
    }
    for symbol in symbols {
        let _ = writeln!(page, "- {}", signature(symbol));
    }
}

/// One entry, written the way it would be read in a script.
fn signature(symbol: &Symbol) -> String {
    match symbol {
        Symbol::Value { name, type_name } => format!("`{name}`: `{type_name}`"),
        Symbol::Function {
            name,
            params,
            returns,
        } => format!("`{name}({})` → `{returns}`", params.join(", ")),
    }
}

#[cfg(test)]
mod tests {
    use super::{render, signature};
    use crate::decay::{Symbol, describe};

    #[test]
    fn a_call_reads_as_a_signature() {
        let symbol = Symbol::Function {
            name: "axis".to_owned(),
            params: vec!["String".to_owned(), "String".to_owned()],
            returns: "f32".to_owned(),
        };
        assert_eq!(signature(&symbol), "`axis(String, String)` → `f32`");
    }

    #[test]
    fn the_page_names_every_type_the_description_carries() {
        let api = describe();
        let page = render(&api);
        for namespace in &api.types {
            assert!(
                page.contains(&format!("### `{}`", namespace.name)),
                "{} has a section",
                namespace.name
            );
        }
    }
}
