[package]
name = "sindri-render"
description = "Shared renderers and render-pass building blocks for Sindri"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck.workspace = true
glam.workspace = true
glyphon.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[lints]
workspace = true
